### ISSUE TITLE
Allow setting attributes on publish

### ISSUE THREAD

**Issue by Sytten** [k-yomo/pubsub_cli#20]
Would nice if we could add attributes to the message.
Thanks!

**Comment by k-yomo** [comment]
@Sytten 
Thanks for filing a feature request!

I added `-a / --atribute` option to set attributes.
When you want to add multiple attributes `-a k1=v1 -a k2=v2` works.

**Comment by Sytten** [comment]
Awesome, thanks! Love your tool
