### ISSUE TITLE
Add a command to create topics

### ISSUE THREAD

**Issue by ledouxpl** [k-yomo/pubsub_cli#62]
I stumbled across your project looking for a CLI letting me create topic and subscriptions against the pubsub emulator and was a bit surprised to see it did not offer explicit topic creation.

I think it would be a great addition, as I would like to be able to create topics without creating subscriptions.

**Comment by k-yomo** [comment]
Thank you for the feedback!
It didn't exist since we haven't experienced the case.  But making it possible to create topic makes sense!
I'll add it soon!

**Comment by k-yomo** [comment]
@ledouxpl 
Released v1.7.0 which has `create_topic` command!
